# -*- coding: utf-8 -*-
"""ds4200 final project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cq39BD7JdA4uGKwMPrvr4S0T5gvu4jRS

## DS4200 final project: Transit Access Inequality Across Boston Neighborhoods
## By: Numa Ali, Maira Padani and Saiuri Parimi

##### Introduction

Public transportation plays an important role in shaping access to jobs, resources, and daily mobility in Boston. However, both transit reliability and infrastructure are not evenly distributed across neighborhoods. This project analyzes MBTA transit prediction accuracy data alongside neighborhood-level socioeconomic indicators to examine whether areas with higher vulnerability also experience lower transit reliability. By combining these datasets, we aim to identify patterns of inequality in transit performance and better understand how service quality may differ across communities.
"""

#from google.colab import drive
#drive.mount('/content/drive')

"""### Part 1: cleaning both the datasets


"""

import pandas as pd

# Load data
import pandas as pd

df = pd.read_csv("rapid_transit_and_bus_prediction_accuracy_data.csv")

# Clean column names
df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")

# Preview columns
print(df.columns)

# FIX DATE COLUMN (auto-detect)
date_col = [col for col in df.columns if "week" in col][0]
df[date_col] = pd.to_datetime(df[date_col])

# FIX KEY COLUMNS
route_col = [col for col in df.columns if "route" in col][0]
mode_col = [col for col in df.columns if "mode" in col][0]

# fix accurate column
accurate_matches = [col for col in df.columns if "accurate" in col or "correct" in col]
accurate_col = accurate_matches[0]

# fix total column (more flexible)
total_matches = [col for col in df.columns if "total" in col or "prediction" in col]
total_col = total_matches[0]

#  CREATE FEATURES
df['accuracy_rate'] = df[accurate_col] / df[total_col]

# Rolling average
df = df.sort_values(date_col)
df['rolling_accuracy'] = df.groupby(route_col)['accuracy_rate'].transform(
    lambda x: x.rolling(4, min_periods=1).mean()
)

# Clean categories
df[mode_col] = df[mode_col].astype(str).str.lower()

# Remove bad rows
df = df.dropna(subset=['accuracy_rate'])
df = df[df[total_col] > 0]

# Final preview
df.head()

import pandas as pd

# Load data
survey = pd.read_csv("MBTA_2024_System-Wide_Passenger_Survey.csv")

# Clean column names
survey.columns = survey.columns.str.lower().str.strip().str.replace(" ", "_")

print(survey.columns)

# LONG → WIDE
survey_wide = survey.pivot_table(
    index=['service_mode', 'reporting_group'],   # grouping level
    columns='measure',                           # question
    values='weighted_percent',                   # values
    aggfunc='first'
).reset_index()

# Clean column names
survey_wide.columns.name = None
survey_wide.columns = survey_wide.columns.str.lower().str.replace(" ", "_")

# Fill missing
survey_wide = survey_wide.fillna(0)

# Preview
survey_wide.head()

import pandas as pd

#  LOAD DATA
df = pd.read_csv("rapid_transit_and_bus_prediction_accuracy_data.csv")

#  CLEAN COLUMN NAMES
df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")

#  SET CORRECT COLUMNS
date_col = 'weekly'
route_col = 'route_id'
mode_col = 'mode'
accurate_col = 'num_accurate_predictions'
total_col = 'num_predictions'

#  FIX DATA TYPES (IMPORTANT)
df[accurate_col] = pd.to_numeric(df[accurate_col], errors='coerce')
df[total_col] = pd.to_numeric(df[total_col], errors='coerce')

#  FEATURE ENGINEERING

# 1. Accuracy rate
df['accuracy_rate'] = df[accurate_col] / df[total_col]

# 2. Error rate (NEW FEATURE)
df['error_rate'] = 1 - df['accuracy_rate']

# 3. Accuracy category
df['accuracy_category'] = pd.cut(
    df['accuracy_rate'],
    bins=[0, 0.5, 0.7, 0.85, 1],
    labels=['low', 'medium', 'high', 'very_high']
)

# 4. Time features
df[date_col] = pd.to_datetime(df[date_col])
df['year'] = df[date_col].dt.year
df['month'] = df[date_col].dt.month

# 5. Rolling accuracy (trend smoothing)
df = df.sort_values(date_col)
df['rolling_accuracy'] = df.groupby(route_col)['accuracy_rate'].transform(
    lambda x: x.rolling(4, min_periods=1).mean()
)

# 6. Route-level average accuracy
route_avg = df.groupby(route_col)['accuracy_rate'].mean()
df['route_avg_accuracy'] = df[route_col].map(route_avg)

# 7. Route performance category
df['route_performance'] = df['route_avg_accuracy'].apply(
    lambda x: 'high' if x > 0.85 else 'low'
)

# 8. Clean mode column
df[mode_col] = df[mode_col].astype(str).str.lower().str.strip()

#  REMOVE BAD DATA
df = df.dropna(subset=['accuracy_rate'])
df = df[df[total_col] > 0]

df.head()

# Setup for visualizations (extra cleaning)

df = pd.read_csv("rapid_transit_and_bus_prediction_accuracy_data.csv")
df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")
df['num_accurate_predictions'] = pd.to_numeric(df['num_accurate_predictions'], errors='coerce')
df['num_predictions'] = pd.to_numeric(df['num_predictions'], errors='coerce')
df['accuracy_rate'] = df['num_accurate_predictions'] / df['num_predictions']
df['error_rate'] = 1 - df['accuracy_rate']
df['weekly'] = pd.to_datetime(df['weekly'])
df['year'] = df['weekly'].dt.year
df['month'] = df['weekly'].dt.month
df = df.dropna(subset=['accuracy_rate'])
df = df[df['num_predictions'] > 0]
df['mode'] = df['mode'].astype(str).str.lower().str.strip()

#  reload & clean survey data
survey = pd.read_csv("MBTA_2024_System-Wide_Passenger_Survey.csv")
survey.columns = survey.columns.str.lower().str.strip().str.replace(" ", "_")

print(f"Prediction data: {df.shape[0]} rows, {df.shape[1]} columns")
print(f"Survey data:     {survey.shape[0]} rows, {survey.shape[1]} columns")
print("Ready for visualizations.")

"""### Part 2: creating altair  """

# VIZ 1 — Altair — Prediction Accuracy Over Time (Brush)
import altair as alt

# Aggregate weekly accuracy by mode
time_mode = (
    df.groupby(['weekly', 'mode'])
    .agg(tp=('num_predictions', 'sum'), ta=('num_accurate_predictions', 'sum'))
    .reset_index()
)
time_mode['accuracy'] = (time_mode['ta'] / time_mode['tp'] * 100).round(2)

# Pivot to compute difference between bus and subway
pivot = time_mode.pivot(index='weekly', columns='mode', values='accuracy').reset_index()
pivot['gap'] = (pivot['bus'] - pivot['subway']).abs()

# Brush selection
brush = alt.selection_interval(encodings=['x'])

# Base line chart
base = alt.Chart(time_mode).mark_line(strokeWidth=2).encode(
    x=alt.X('weekly:T'),
    y=alt.Y('accuracy:Q'),
    color=alt.Color('mode:N',
        scale=alt.Scale(domain=['bus', 'subway'], range=['#e67e22', '#2980b9']),
        legend=alt.Legend(title='Transit Mode')
    ),
    tooltip=[
        alt.Tooltip('weekly:T', title='Week'),
        alt.Tooltip('mode:N', title='Mode'),
        alt.Tooltip('accuracy:Q', title='Accuracy (%)', format='.1f')
    ]
)

# highlight divergence periods
highlight = alt.Chart(pivot).mark_circle(size=60, color='red').encode(
    x='weekly:T',
    y='bus:Q',
    tooltip=[
        alt.Tooltip('weekly:T'),
        alt.Tooltip('gap:Q', title='Accuracy Gap', format='.1f')
    ]
).transform_filter(
    alt.datum.gap > 5  # highlight when difference > 5%
)

# Upper chart (detail view)
upper = (base + highlight).encode(
    x=alt.X('weekly:T', scale=alt.Scale(domain=brush), title=None),
    y=alt.Y('accuracy:Q', scale=alt.Scale(domain=[65, 95]), title='Accuracy (%)')
).properties(
    width=700,
    height=280,
    title='Bus vs. Subway Prediction Accuracy Over Time (Highlighting Divergence)'
)

# Lower chart (overview with brush)
lower = base.properties(
    width=700,
    height=60
).add_params(brush).encode(
    x=alt.X('weekly:T', title='Drag to explore specific time periods'),
    y=alt.Y('accuracy:Q', title=None, scale=alt.Scale(domain=[65, 95]), axis=None)
)

chart1 = alt.vconcat(upper, lower).configure_view(strokeWidth=0)

chart1
chart1.save("site/altair/chart1.json")

"""Visualization 1 Takeaway:

Bus predictions consistently outperform subway predictions by 3–8 percentage points across the full 2020–2026 period. The gap has widened since late 2023,with subway accuracy declining into the mid-to-high 70s while bus accuracy
remains stable in the mid-80s. Use the brush on the lower panel to zoom into any date range for closer inspection.

### Part 3: Visual in JavaScript
"""

# VIZ 2 — D3 — Accuracy by Time Horizon (Hover Tooltip)

from IPython.display import HTML

# Prepare data
bin_mode = (
    df.groupby(['mode', 'bin'])
    .agg(tp=('num_predictions', 'sum'), ta=('num_accurate_predictions', 'sum'))
    .reset_index()
)
bin_mode['accuracy'] = (bin_mode['ta'] / bin_mode['tp']).round(4)

bin_export = bin_mode[['mode', 'bin', 'accuracy']]
bin_json = bin_export.to_json(orient='records')
bin_export.to_json("site/data/viz2.json", orient="records")

viz2_html = f"""
<div id="viz2" style="background:#fff;padding:20px;border-radius:8px;border:1px solid #ddd;font-family:sans-serif"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.5/d3.min.js"></script>
<script>
(function() {{
const data = {bin_json};
const bins = ['0-3 min','3-6 min','6-12 min','12-30 min'];
const modes = ['bus','subway'];
const colors = {{bus:'#e67e22',subway:'#2980b9'}};
const labels = {{bus:'Bus',subway:'Subway'}};

const W=700,H=340,M={{t:30,r:30,b:50,l:60}};
const iW=W-M.l-M.r, iH=H-M.t-M.b;

const svg = d3.select('#viz2').append('svg')
    .attr('viewBox','0 0 '+W+' '+H).attr('width','100%');

// Title
svg.append('text').attr('x',W/2).attr('y',20).attr('text-anchor','middle')
    .style('font-size','15px').style('font-weight','600')
    .text('Prediction Accuracy by Time Horizon: Bus vs. Subway');

const g = svg.append('g').attr('transform','translate('+M.l+','+M.t+')');

const x0 = d3.scaleBand().domain(bins).range([0,iW]).padding(0.25);
const x1 = d3.scaleBand().domain(modes).range([0,x0.bandwidth()]).padding(0.08);
const y  = d3.scaleLinear().domain([0.70, 0.92]).range([iH, 0]);

// Axes
g.append('g').attr('transform','translate(0,'+iH+')')
    .call(d3.axisBottom(x0).tickSize(0))
    .selectAll('text').style('font-size','12px');
g.append('g')
    .call(d3.axisLeft(y).ticks(5).tickFormat(d=>(d*100).toFixed(0)+'%'))
    .selectAll('text').style('font-size','11px');
g.append('text').attr('transform','rotate(-90)').attr('x',-iH/2).attr('y',-45)
    .attr('text-anchor','middle').style('font-size','12px').text('Accuracy (%)');

// Tooltip
const tip = d3.select('#viz2').append('div')
    .style('position','absolute').style('background','rgba(0,0,0,0.85)')
    .style('color','#fff').style('padding','6px 10px').style('border-radius','4px')
    .style('font-size','12px').style('pointer-events','none').style('display','none');

// Bars
bins.forEach(bin => {{
    modes.forEach(mode => {{
        const d = data.find(r => r.bin===bin && r.mode===mode);
        if (!d) return;
        g.append('rect')
            .attr('x', x0(bin) + x1(mode))
            .attr('y', y(d.accuracy))
            .attr('width', x1.bandwidth())
            .attr('height', iH - y(d.accuracy))
            .attr('fill', colors[mode])
            .attr('rx', 3)
            .on('mouseover', function(evt) {{
                d3.select(this).attr('opacity', 0.8);
                tip.style('display','block')
                   .html('<b>'+labels[mode]+'</b> · '+bin+'<br>Accuracy: <b>'+(d.accuracy*100).toFixed(1)+'%</b>');
            }})
            .on('mousemove', function(evt) {{
                tip.style('left',(evt.offsetX+15)+'px').style('top',(evt.offsetY-10)+'px');
            }})
            .on('mouseout', function() {{
                d3.select(this).attr('opacity', 1);
                tip.style('display','none');
            }});
    }});
}});

// Legend
const lg = g.append('g').attr('transform','translate('+(iW-120)+',5)');
modes.forEach((m,i) => {{
    lg.append('rect').attr('x',0).attr('y',i*22).attr('width',14).attr('height',14)
        .attr('fill',colors[m]).attr('rx',2);
    lg.append('text').attr('x',19).attr('y',i*22+12).text(labels[m])
        .style('font-size','12px');
}});
}})();
</script>
"""
HTML(viz2_html)

"""Vizualization 2 Takeaway:

Bus and subway show opposite accuracy patterns across prediction windows.Bus accuracy improves with longer horizons (81% at 0–3 min to 87% at 12–30 min), while subway accuracy drops from 86% at 0–3 min to just 77% at 12–30 min.Hover over any bar to see exact values.

### Part 4: Creating 4 interactive visualizations
"""

# VIZ 3 — D3 — Rider Demographics by Mode (Dropdown Filter)

# VIZ 3 — D3 — Rider Demographics by Mode (Dropdown + Click Interaction)
# print("aggregation levels:")
# print(sorted(survey['aggregation_level'].dropna().unique()))

# print("\nservice modes:")
# print(sorted(survey['service_mode'].dropna().unique()))

# print("\nmeasures:")
# print(sorted(survey['measure'].dropna().unique()))

# print("\nUsable Cars categories:")
# print(sorted(survey[survey['measure'] == 'Usable Cars']['category'].dropna().astype(str).unique()))

# print("\nTitle VI Low-Income categories:")
# print(sorted(survey[survey['measure'] == 'Title VI Low-Income']['category'].dropna().astype(str).unique()))

# print("\nTitle VI Minority categories:")
# print(sorted(survey[survey['measure'] == 'Title VI Minority']['category'].dropna().astype(str).unique()))
import os
from IPython.display import HTML

os.makedirs("site/data", exist_ok=True)

demo = survey.copy()

demo['aggregation_level'] = demo['aggregation_level'].astype(str).str.strip()

demo['service_mode'] = demo['service_mode'].astype(str).str.strip()

demo['measure'] = demo['measure'].astype(str).str.strip()

demo['category'] = demo['category'].astype(str).str.strip()

demo = demo[

    demo['aggregation_level'] == 'Service Mode'

]

demo = demo[demo['service_mode'].isin([

    'Bus',

    'Rapid Transit or Bus Rapid Transit',

    'Commuter Rail',

    'Ferry'

])]

low_income = demo[
    (demo['measure'] == 'Title VI Low-Income') &
    (demo['category'].str.lower() == 'yes')
][['service_mode', 'weighted_percent']].rename(columns={'weighted_percent': 'pct_low_income'})

minority = demo[
    (demo['measure'] == 'Title VI Minority') &
    (demo['category'].str.lower() == 'yes')
][['service_mode', 'weighted_percent']].rename(columns={'weighted_percent': 'pct_minority'})

zero_car = demo[
    (demo['measure'] == 'Usable Cars') &
    (demo['category'] == '0')
][['service_mode', 'weighted_percent']].rename(columns={'weighted_percent': 'pct_zero_car'})

demo_wide = low_income.merge(minority, on='service_mode', how='outer')
demo_wide = demo_wide.merge(zero_car, on='service_mode', how='outer').fillna(0)

demo_wide = demo_wide.rename(columns={'service_mode': 'mode'})

for col in ['pct_low_income', 'pct_minority', 'pct_zero_car']:
    demo_wide[col] = (demo_wide[col] * 100).round(1)

print(demo_wide)

demo_json = demo_wide.to_json(orient='records')
demo_wide.to_json("site/data/viz3.json", orient="records")
print(demo_json)

viz3_html = f"""
<div id="viz3" style="background:#fff;padding:20px;border-radius:8px;border:1px solid #ddd;font-family:sans-serif;position:relative">

<div style="margin-bottom:10px">
  <label style="font-size:13px;font-weight:600;">Demographic measure: </label>
  <select id="demo-select" style="font-size:13px;padding:3px 6px;border-radius:4px;border:1px solid #ccc">
    <option value="pct_low_income">% Title VI Low-Income</option>
    <option value="pct_minority">% Title VI Minority</option>
    <option value="pct_zero_car">% Zero-Vehicle Households</option>
  </select>
</div>

<div id="viz3-chart"></div>

</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.5/d3.min.js"></script>

<script>
(function() {{

const data = {demo_json};

const mOrder = ['Bus','Rapid Transit or Bus Rapid Transit','Commuter Rail','Ferry'];
const mShort = {{
    'Bus':'Bus',
    'Rapid Transit or Bus Rapid Transit':'Rapid Transit',
    'Commuter Rail':'Commuter Rail',
    'Ferry':'Ferry'
}};

const mColors = {{
    'Bus':'#e67e22',
    'Rapid Transit or Bus Rapid Transit':'#2980b9',
    'Commuter Rail':'#27ae60',
    'Ferry':'#8e44ad'
}};

const W=700,H=300,M={{t:30,r:50,b:30,l:135}};
const iW=W-M.l-M.r, iH=H-M.t-M.b;

const svg = d3.select('#viz3-chart').append('svg')
    .attr('viewBox','0 0 '+W+' '+H)
    .attr('width','100%');

svg.append('text')
    .attr('x',W/2)
    .attr('y',18)
    .attr('text-anchor','middle')
    .attr('id','viz3-title')
    .style('font-size','15px')
    .style('font-weight','600')
    .text('Rider Demographics by Transit Mode');

const g = svg.append('g')
    .attr('transform','translate('+M.l+','+M.t+')');

const yB = d3.scaleBand()
    .domain(mOrder)
    .range([0,iH])
    .padding(0.3);

const x = d3.scaleLinear()
    .domain([0,100])
    .range([0,iW]);

g.append('g')
    .call(d3.axisLeft(yB).tickFormat(d=>mShort[d]).tickSize(0));

g.append('g')
    .attr('transform','translate(0,'+iH+')')
    .call(d3.axisBottom(x).ticks(5).tickFormat(d=>d+'%'));

let selected = null;

const bars = g.selectAll('.dbar')
    .data(data)
    .enter()
    .append('rect')
    .attr('class','dbar')
    .attr('y', d => yB(d.mode))
    .attr('height', yB.bandwidth())
    .attr('rx', 4)
    .attr('fill', d => mColors[d.mode])
    .style('cursor','pointer')
    .on('click', function(event, d) {{
        selected = (selected === d.mode) ? null : d.mode;

        bars.style('opacity', b =>
            (!selected || b.mode === selected) ? 1 : 0.3
        );
    }});

const vals = g.selectAll('.vlbl')
    .data(data)
    .enter()
    .append('text')
    .attr('class','vlbl')
    .attr('y', d => yB(d.mode) + yB.bandwidth()/2 + 5)
    .style('font-size','12px')
    .style('font-weight','600');

function update(measure) {{

    const titles = {{
        pct_low_income: '% Title VI Low-Income Riders by Mode',
        pct_minority: '% Title VI Minority Riders by Mode',
        pct_zero_car: '% Zero-Vehicle Households by Mode'
    }};

    d3.select('#viz3-title').text(titles[measure]);

    bars.transition().duration(500)
        .attr('x', 0)
        .attr('width', d => x(d[measure] || 0));

    vals.transition().duration(500)
        .attr('x', d => x(d[measure] || 0) + 5)
        .text(d => (d[measure] || 0).toFixed(1) + '%');
}}

update('pct_low_income');

document.getElementById('demo-select')
    .addEventListener('change', function() {{
        update(this.value);
    }});

}})();
</script>
"""

HTML(viz3_html)
    

"""Visualization #3 Takeaway: Demographic patterns vary significantly across transit modes, with bus riders representing the most economically vulnerable group, showing the highest shares of low-income, minority, and zero-vehicle households. In contrast, ferry riders reflect a more affluent profile with substantially lower percentages across these measures. This highlights how different transit systems serve distinct populations, and the dropdown interaction allows for deeper comparison across demographic dimensions.


"""

# VIZ 4 — Altair — Subway Accuracy vs. Demographics (Tooltip)
import altair as alt

# Subway line accuracy
sub_acc = (
    df[df['mode'] == 'subway']
    .groupby('route_id')
    .agg(tp=('num_predictions', 'sum'), ta=('num_accurate_predictions', 'sum'))
    .reset_index()
)
sub_acc['accuracy'] = (sub_acc['ta'] / sub_acc['tp'] * 100).round(2)

# Map subway route_id → survey service_mode
route_to_survey = {
    'Blue':    'Rapid Transit or Bus Rapid Transit - Blue Line',
    'Green-B': 'Rapid Transit or Bus Rapid Transit - Green Line',
    'Green-C': 'Rapid Transit or Bus Rapid Transit - Green Line',
    'Green-D': 'Rapid Transit or Bus Rapid Transit - Green Line',
    'Green-E': 'Rapid Transit or Bus Rapid Transit - Green Line',
    'Mattapan':'Rapid Transit or Bus Rapid Transit - Mattapan Trolley',
    'Orange':  'Rapid Transit or Bus Rapid Transit - Orange Line',
    'Red':     'Rapid Transit or Bus Rapid Transit - Red Line',
}

scatter_rows = []
for _, row in sub_acc.iterrows():
    smode = route_to_survey[row['route_id']]
    s = survey[survey['service_mode'] == smode]
    li = s[(s['measure'] == 'Title VI Low-Income') & (s['category'] == 'Yes')]
    mi = s[(s['measure'] == 'Title VI Minority') & (s['category'] == 'Yes')]
    scatter_rows.append({
        'Line': row['route_id'],
        'Accuracy (%)': row['accuracy'],
        '% Minority Riders': round(mi.iloc[0]['weighted_percent'] * 100, 1) if len(mi) else 0,
        '% Low-Income Riders': round(li.iloc[0]['weighted_percent'] * 100, 1) if len(li) else 0,
        'Total Predictions': int(row['tp'])
    })
scatter_df = pd.DataFrame(scatter_rows)

# Interactive selection
selection = alt.selection_point(fields=['Line'], bind='legend')

# Base encoding
base = alt.Chart(scatter_df).encode(
    x=alt.X('% Minority Riders:Q',
            title='Minority Riders (%)',
            scale=alt.Scale(zero=False)),
    y=alt.Y('Accuracy (%):Q',
            title='Prediction Accuracy (%)',
            scale=alt.Scale(domain=[65, 95]))
)

# Points (NOW color = low-income for added depth)
points = base.mark_circle(
    stroke='#333', strokeWidth=1
).encode(
    size=alt.Size('Total Predictions:Q',
                  scale=alt.Scale(range=[100, 600]),
                  legend=alt.Legend(title='Total Predictions', format='.2s')),
    color=alt.Color('% Low-Income Riders:Q',
                    scale=alt.Scale(scheme='blues'),
                    title='Low-Income Riders (%)'),
    opacity=alt.condition(selection, alt.value(1), alt.value(0.2)),
    tooltip=[
        alt.Tooltip('Line:N'),
        alt.Tooltip('Accuracy (%):Q', format='.1f'),
        alt.Tooltip('% Minority Riders:Q', format='.1f'),
        alt.Tooltip('% Low-Income Riders:Q', format='.1f'),
        alt.Tooltip('Total Predictions:Q', format=',.0f')
    ]
).add_selection(selection)

# Labels (makes small dataset stronger)
labels = base.mark_text(
    align='left',
    dx=5,
    dy=-5,
    fontSize=10
).encode(
    text='Line:N'
)

# Regression line
trendline = base.transform_regression(
    '% Minority Riders', 'Accuracy (%)'
).mark_line(
    color='black',
    strokeDash=[5,5]
)

# Final chart
chart4 = (points + trendline + labels).properties(
    width=650,
    height=350,
    title='Subway Prediction Accuracy vs. Minority & Low-Income Ridership'
).configure_view(strokeWidth=0)

chart4
chart4.save("site/altair/chart4.json")

"""Visualization #4 Takeaway: While Mattapan shows both high minority ridership (76%) and high prediction accuracy (92%), and Green Line E has the lowest accuracy (69%), the overall trend indicates only a weak relationship between demographics and accuracy. This suggests that prediction performance is not strongly driven by rider composition, and other operational factors likely play a larger role. Hover over each point for additional details on low-income ridership and total predictions.

"""

# VIZ 5 — D3 — Racial Composition Stacked Bar (Click Highlight)

from IPython.display import HTML

# Extract race data at service-mode level
sm = survey[survey['aggregation_level'] == 'Service Mode']
race = sm[sm['measure'] == 'Race'][['service_mode', 'category', 'weighted_percent']].copy()
race = race[race['service_mode'].isin(
    ['Bus', 'Commuter Rail', 'Rapid Transit or Bus Rapid Transit', 'Ferry']
)]
race['weighted_percent'] = (race['weighted_percent'] * 100).round(1)
race_json = race.to_json(orient='records')
race.to_json("site/data/viz5.json", orient="records")

viz5_html = f"""
<div id="viz5" style="background:#fff;padding:20px;border-radius:8px;border:1px solid #ddd;font-family:sans-serif;position:relative">
<div id="viz5-legend" style="display:flex;flex-wrap:wrap;gap:12px;margin-bottom:8px;font-size:12px"></div>
<div id="viz5-chart"></div>
<p style="font-size:11px;color:#888;margin-top:6px">Click a race/ethnicity in the legend to highlight it across all modes. Click again to reset.</p>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.5/d3.min.js"></script>
<script>
(function() {{
const raw = {race_json};
const rOrder = ['White','Black or African American','Asian','Other',
  'American Indian or Alaska Native','Middle Eastern or North African',
  'Native Hawaiian or other Pacific Islander','Prefer not to say'];
const rColors = ['#3498db','#e74c3c','#f39c12','#95a5a6','#1abc9c','#9b59b6','#e67e22','#bdc3c7'];
const mOrder = ['Bus','Rapid Transit or Bus Rapid Transit','Commuter Rail','Ferry'];
const mShort = {{'Bus':'Bus','Rapid Transit or Bus Rapid Transit':'Rapid Transit',
                'Commuter Rail':'Commuter Rail','Ferry':'Ferry'}};

// Pivot
const piv = {{}};
mOrder.forEach(m => {{ piv[m] = {{}}; rOrder.forEach(r => piv[m][r] = 0); }});
raw.forEach(d => {{ if(piv[d.service_mode] && rOrder.includes(d.category)) piv[d.service_mode][d.category] = d.weighted_percent; }});
const stackData = mOrder.map(m => {{ const o = {{mode:m}}; rOrder.forEach(r => o[r] = piv[m][r]); return o; }});

const W=700,H=300,M={{t:30,r:28,b:30,l:135}};
const iW=W-M.l-M.r, iH=H-M.t-M.b;
const svg = d3.select('#viz5-chart').append('svg')
    .attr('viewBox','0 0 '+W+' '+H).attr('width','100%');

svg.append('text').attr('x',W/2).attr('y',18).attr('text-anchor','middle')
    .style('font-size','15px').style('font-weight','600')
    .text('Racial Composition of Riders by Transit Mode');

const g = svg.append('g').attr('transform','translate('+M.l+','+M.t+')');
const yB = d3.scaleBand().domain(mOrder).range([0,iH]).padding(0.3);
const x  = d3.scaleLinear().domain([0,100]).range([0,iW]);
const color = d3.scaleOrdinal().domain(rOrder).range(rColors);

g.append('g').call(d3.axisLeft(yB).tickFormat(d=>mShort[d]).tickSize(0)).selectAll('text').style('font-size','12px');
g.append('g').attr('transform','translate(0,'+iH+')').call(d3.axisBottom(x).ticks(5).tickFormat(d=>d+'%')).selectAll('text').style('font-size','11px');

const stack = d3.stack().keys(rOrder)(stackData);
let activeRace = null;

// Tooltip
const tip = d3.select('#viz5').append('div')
    .style('position','absolute').style('background','rgba(0,0,0,0.85)')
    .style('color','#fff').style('padding','6px 10px').style('border-radius','4px')
    .style('font-size','12px').style('pointer-events','none').style('display','none');

const layers = g.selectAll('.layer').data(stack).enter().append('g').attr('class','layer');
layers.each(function(ld) {{
    d3.select(this).selectAll('rect').data(ld).enter().append('rect')
        .attr('y', d => yB(d.data.mode))
        .attr('x', d => x(d[0]))
        .attr('width', d => x(d[1]) - x(d[0]))
        .attr('height', yB.bandwidth())
        .attr('fill', color(ld.key))
        .attr('stroke','#fff').attr('stroke-width',0.5)
        .on('mouseover', function(evt, d) {{
            tip.style('display','block')
               .html('<b>'+ld.key+'</b><br>'+mShort[d.data.mode]+': '+(d[1]-d[0]).toFixed(1)+'%');
        }})
        .on('mousemove', function(evt) {{
            tip.style('left',(evt.offsetX+15)+'px').style('top',(evt.offsetY-10)+'px');
        }})
        .on('mouseout', function() {{ tip.style('display','none'); }});
}});

// Legend with click-to-highlight
const legend = d3.select('#viz5-legend');
rOrder.forEach((r, i) => {{
    const item = legend.append('div')
        .style('display','flex').style('align-items','center').style('gap','4px')
        .style('cursor','pointer').style('user-select','none');
    item.append('div').style('width','13px').style('height','13px')
        .style('border-radius','2px').style('background',rColors[i]).style('flex-shrink','0');
    item.append('span').text(r);
    item.on('click', function() {{
        if (activeRace === r) {{
            activeRace = null;
            layers.selectAll('rect').transition().duration(300).style('opacity', 1);
        }} else {{
            activeRace = r;
            layers.selectAll('rect').transition().duration(300)
                .style('opacity', function() {{
                    return d3.select(this.parentNode).datum().key === r ? 1 : 0.12;
                }});
        }}
    }});
}});
}})();
</script>
"""
HTML(viz5_html)

"""Visualization #5 Takeaway: Bus riders are the most racially diverse: 35% identify as Black or African American compared to 21% on rapid transit and 9% on the ferry. White riders make up 81% of ferry passengers but only 43% of bus passengers. Click any category in the legend to isolate it across all four modes.



"""

#VIZ 6 — D3 — Subway Lines Over Time (Toggle + Crosshair)

from IPython.display import HTML

# Aggregate subway accuracy by week and route
sub_ts = (
    df[df['mode'] == 'subway']
    .groupby(['weekly', 'route_id'])
    .agg(tp=('num_predictions', 'sum'), ta=('num_accurate_predictions', 'sum'))
    .reset_index()
)
sub_ts['accuracy'] = (sub_ts['ta'] / sub_ts['tp']).round(4)
sub_ts['weekly'] = sub_ts['weekly'].dt.strftime('%Y-%m-%d')
sub_ts = sub_ts.dropna(subset=['accuracy'])

# Sample every 4th week to keep the HTML manageable
dates_sorted = sorted(sub_ts['weekly'].unique())
keep_dates = set(dates_sorted[::4] + [dates_sorted[-1]])
sub_ts_sampled = sub_ts[sub_ts['weekly'].isin(keep_dates)]
sub_ts_export = sub_ts_sampled[['weekly', 'route_id', 'accuracy']]
sub_ts_json = sub_ts_export.to_json(orient='records')
sub_ts_export.to_json("site/data/viz6.json", orient="records")

viz6_html = f"""
<div id="viz6" style="background:#fff;padding:20px;border-radius:8px;border:1px solid #ddd;font-family:sans-serif;position:relative">
<div id="viz6-legend" style="display:flex;flex-wrap:wrap;gap:14px;margin-bottom:8px;font-size:12px"></div>
<div id="viz6-chart"></div>
<p style="font-size:11px;color:#888;margin-top:6px">Click a line name in the legend to show/hide it. Hover over the chart to see values at any date.</p>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.5/d3.min.js"></script>
<script>
(function() {{
const raw = {sub_ts_json};
const lines = ['Blue','Green-B','Green-C','Green-D','Green-E','Mattapan','Orange','Red'];
const lc = {{
    'Blue':'#003DA5','Green-B':'#00843D','Green-C':'#2ECC71',
    'Green-D':'#27AE60','Green-E':'#16A085','Mattapan':'#8B4513',
    'Orange':'#ED8B00','Red':'#DA291C'
}};
const parsed = raw.map(d => ({{...d, date:new Date(d.weekly), acc:d.accuracy*100}}));
const byLine = {{}};
lines.forEach(l => {{ byLine[l] = parsed.filter(d => d.route_id===l).sort((a,b) => a.date-b.date); }});

const W=700,H=400,M={{t:30,r:30,b:40,l:50}};
const iW=W-M.l-M.r, iH=H-M.t-M.b;
const svg = d3.select('#viz6-chart').append('svg')
    .attr('viewBox','0 0 '+W+' '+H).attr('width','100%');

svg.append('text').attr('x',W/2).attr('y',18).attr('text-anchor','middle')
    .style('font-size','15px').style('font-weight','600')
    .text('Subway Line Prediction Accuracy Over Time');

const g = svg.append('g').attr('transform','translate('+M.l+','+M.t+')');
const xS = d3.scaleTime().domain(d3.extent(parsed,d=>d.date)).range([0,iW]);
const yS = d3.scaleLinear().domain([45,100]).range([iH,0]);

g.append('g').attr('transform','translate(0,'+iH+')').call(d3.axisBottom(xS).ticks(8)).selectAll('text').style('font-size','10px');
g.append('g').call(d3.axisLeft(yS).ticks(6).tickFormat(d=>d+'%')).selectAll('text').style('font-size','10px');
g.append('text').attr('transform','rotate(-90)').attr('x',-iH/2).attr('y',-38)
    .attr('text-anchor','middle').style('font-size','11px').text('Accuracy (%)');

const lineGen = d3.line().x(d=>xS(d.date)).y(d=>yS(d.acc)).curve(d3.curveMonotoneX);
const vis = {{}};
const paths = {{}};
lines.forEach(l => {{
    vis[l] = true;
    paths[l] = g.append('path').datum(byLine[l])
        .attr('fill','none').attr('stroke',lc[l]).attr('stroke-width',1.8)
        .attr('d',lineGen).attr('opacity',0.85);
}});

// Crosshair
const hLine = g.append('line').attr('y1',0).attr('y2',iH)
    .attr('stroke','#999').attr('stroke-width',1).attr('stroke-dasharray','3,3').style('display','none');
const hDots = g.append('g');
const tip = d3.select('#viz6').append('div')
    .style('position','absolute').style('background','rgba(0,0,0,0.88)')
    .style('color','#fff').style('padding','8px 12px').style('border-radius','4px')
    .style('font-size','12px').style('pointer-events','none').style('display','none')
    .style('line-height','1.6');

g.append('rect').attr('width',iW).attr('height',iH).attr('fill','transparent')
    .on('mousemove', function(evt) {{
        const [mx] = d3.pointer(evt);
        const date = xS.invert(mx);
        hLine.style('display','block').attr('x1',mx).attr('x2',mx);
        hDots.selectAll('*').remove();
        let html = '<b>'+d3.timeFormat('%b %d, %Y')(date)+'</b><br>';
        lines.forEach(l => {{
            if (!vis[l] || !byLine[l].length) return;
            const cl = byLine[l].reduce((a,b) => Math.abs(b.date-date)<Math.abs(a.date-date)?b:a);
            if (Math.abs(cl.date - date) < 35*24*3600*1000) {{
                hDots.append('circle').attr('cx',xS(cl.date)).attr('cy',yS(cl.acc))
                    .attr('r',4).attr('fill',lc[l]).attr('stroke','#fff').attr('stroke-width',1.5);
                html += '<span style="color:'+lc[l]+'">&#9632;</span> '+l+': '+cl.acc.toFixed(1)+'%<br>';
            }}
        }});
        tip.style('display','block').html(html)
            .style('left',(evt.offsetX+18)+'px').style('top',(evt.offsetY-10)+'px');
    }})
    .on('mouseout', function() {{
        hLine.style('display','none'); hDots.selectAll('*').remove(); tip.style('display','none');
    }});

// Legend with toggle
const legend = d3.select('#viz6-legend');
lines.forEach(l => {{
    const item = legend.append('div')
        .style('display','flex').style('align-items','center').style('gap','5px')
        .style('cursor','pointer').style('user-select','none');
    const swatch = item.append('div').style('width','14px').style('height','14px')
        .style('border-radius','3px').style('background',lc[l]).style('flex-shrink','0');
    const label = item.append('span').text(l);
    item.on('click', function() {{
        vis[l] = !vis[l];
        paths[l].transition().duration(300).attr('opacity', vis[l] ? 0.85 : 0.05);
        item.style('opacity', vis[l] ? 1 : 0.35);
    }});
}});
}})();
</script>
"""
HTML(viz6_html)

"""Visualization #6 Takeaway:
Green Line E consistently sits at the bottom (often below 70%), while Mattapan and Blue hold the top above 85–90%. The gap between best and worst can exceed 30 percentage points in the same week. The Red Line shows a downward trend starting late 2024. Click line names in the legend to isolate specific lines;
hover to see exact values at any date.

###Summary of Findings and Future Work

The visualizations show that prediction accuracy varies across transit modes and routes. Bus predictions tend to be more stable over time, while subway performance varies more across lines, with some routes such as the Green Line E consistently underperforming. These differences suggest that reliability is uneven and may affect rider experience across communities. The demographic analysis also indicates that more vulnerable populations rely more on certain transit modes, raising potential equity concerns.

In the future, this work could be improved by incorporating more granular data, such as neighborhood- or station-level information, along with external factors like weather and service disruptions. This would help better explain variation in prediction accuracy and provide a clearer view of how reliability impacts riders.

###Analysis
Our analysis examines how transit prediction reliability varies across modes, routes, and time, and how these differences may contribute to infrastructure inequality in Boston. Using the cleaned dataset, we created additional features such as accuracy rate, error rate, rolling accuracy, and route-level performance categories to better understand reliability patterns.

We first compared prediction accuracy across transit modes and found that bus predictions are generally more stable over time, while subway accuracy varies more across lines and time periods. This suggests that different operational factors affect each mode in distinct ways.

We then analyzed trends over time using rolling accuracy, which helped smooth short-term fluctuations and reveal broader patterns. The results show that prediction accuracy changes over time, indicating that reliability is not constant and may be influenced by operational or seasonal conditions.

At the route level, we identified clear differences in performance. Some routes consistently fall into lower performance categories, indicating areas where riders may experience greater uncertainty and less reliable service.

Finally, by introducing error rate alongside accuracy, we were able to better highlight routes with higher levels of unreliability. Overall, our findings show that transit reliability is unevenly distributed, which may contribute to unequal transit experiences across different communities in Boston.
"""
print(sorted(survey['measure'].dropna().unique()))
